name: Build Action
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch
        type: string
        default: main
        required: true
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ github.event.inputs.ref }}
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: '.tool-versions'
    - name: Install dependencies
      run: |
        npm ci
    - name: Build Action
      run: |
        npm run build
    - name: Update dist
      env:
        INPUT_REF: ${{ inputs.ref }}
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./dist &&
        git commit -m "Update dist"
        git push origin HEAD:"$INPUT_REF"
